name: develop-release
on:
  # deployment to internal ghcr repo only manually triggered
  workflow_dispatch:
  push:
    branches:
      - develop
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: solace-iot-team/solace-amplify-discovery-agent
  VERSION: "0.0.0"
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/checkout@v2

      - name: Set versions properties
        run:  |
          VERSION=$(<version)
          echo "VERSION=$VERSION">> $GITHUB_ENV
          echo "VERSION: $VERSION"
          echo " VERSIONS ARE GETTING IGNORED - ONLY DEV-LATEST IS USED "

      - name: Build and Deploy to Github Docker registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{env.IMAGE_NAME}}:dev-latest
